### ISSUE TITLE
doDensity option needed in the pyridineDensOverlap example

### ISSUE THREAD

**Issue by mondracek** [Probe-Particle/ppafm#90] opened 2023-02-17 13:08 UTC
Another one from the promised series of issues found on the road to getting at least the basic functionality work for me: When I try to run the example in ``ProbeParticleModel/examples/pyridineDensOverlap``, using the commands as provided in ``ProbeParticleModel/examples/pyridineDensOverlap/run.sh``, the script ``generateElFF.py`` crashes at calling the ``subtractCoreDensities`` function because of undefined ``elems_tip``. What needs to be done is calling ``generateElFF.py`` with the ``-doDensity`` option added, like this: 
``generateElFF.py -i sample/LOCPOT.xsf --tip_dens tip/CHGCAR.xsf --Rcore 0.7 -doDensity -E``
Can you enlighten me what is going on here? Is adding the option to the ``run.sh`` script all that it takes to solve the issue or is there something deeper I am missing? What exactly is the option supposed to do?

**Comment by NikoOinonen** [comment] 2023-02-18 04:58
This is a duplicate of #70 which is being fixed by Prokop at the moment.

**Closed by NikoOinonen** 2023-02-18 04:58 UTC
Labels: duplicate
