### ISSUE TITLE
DFT-D3 van der Waals does not work correctly with hydroxyl (-OH) groups

### ISSUE THREAD

**Issue by mondracek** [Probe-Particle/ppafm#257] opened 2024-01-31 10:22 UTC
The van der Waals forces in the `FFvdW_?.xsf ` seem to be too small when calculated over an -OH group.

I first hit into this problem when trying to simulate a cyclodextrin molecule using the full-density based method. Trying to track the problem, I checked that even an isolated .OH radical (O+H pair of atoms) reproduces this problem. The resulting interaction of the CO tip with the hydroxyl group remains repulsive even for distances in which attractive interaction is expected, apparently *because of a negligible (though non-zero) vdW component*.

**Comment by NikoOinonen** [comment] 2024-01-31 11:05
I assume this is using the DFT-D3 vdW, since you are talking about the full-density based model. I was also worrying about the magnitude of the vdW before in relation to the pyridine example. There specifically I found that the standard LJ vdW was too strong compared to the DFT-D3 vdW that was used in the original paper for the FDBM, which is what lead me to implement it also here. I think it might in general be the case that the DFT-D3 contribution is smaller than LJ.

If the vdW is too weak, there are several things you could try:
- It could be that instead of vdW being too weak, the repulsion is too strong. If you haven't tried yet, you could try adjusting the parameters of the Pauli integral, either increasing the exponent (small increments, like 0.05), or decreasing the prefactor.
- Try adjusting the parameters of the DFT-D3 (a1, a2, s6, s8): https://ppafm.readthedocs.io/en/latest/ppafm.ocl.html#ppafm.ocl.field.ForceField_LJC.add_dftd3
- Try switching back to the LJ vdW.

**Comment by mondracek** [comment] 2024-01-31 14:04
@NikoOinonen thanks.
* As for your last suggestion, how do I do it? How can switch to LJ vdW with the full density in PPAFM? (Or perhaps it is actually DFT-D2 rather than LJ, as I definitely do not want the repulsive part of LJ to be combined with the Pauli repulsion from full density.)
* Regarding the suggestions to play with the parameters, well, no, I do not like it. I mean, I can try it just to find out more specifically where the problem is, but that's it. It is still a problem when the default set of parameters fails so badly. I can understand that of course I should not expect DFT-D3 to be absolutely perfect and fail-safe, like no method ever is, nor can any set of parameters be totally universal. One can always find some strange outlier molecule for which the method either fails or for which some tuning of parameters turns out to be the necessary and reasonable thing to do. However, hydroxyl groups are nothing that terribly unusual. If the default parameters fail for them, they are going to fail for most oxygen containing organic molecules. I really think there is a problem we need to solve.
* I will try to find out what the actual value of the C6 coefficient is for oxygen in the troublesome calculations and compare it to e.g. C6 for carbon (if there were order-of magnitude differences, that would indicate a problem). Besides, do you have any simulations with oxygen-containing organic molecule which you believe give reasonable results? I would like to check those if you do.

**Comment by NikoOinonen** [comment] 2024-01-31 15:06
> How can switch to LJ vdW with the full density in PPAFM?

Depends on whether you are using the CPU or the GPU version.
- CPU: Instead of `ppafm-generate-dftd3`, use `ppafm-generate-ljff` with the option `--ffModel vdW` and it will only output the vdW-part of the forcefield
- GPU: In `AFMulator` set  `fdbm_vdw_type = 'LJ'`.

> It is still a problem when the default set of parameters fails so badly.

Yes, probably at least the default Pauli parameters should be adjusted. But I'm not sure what they should be. In the papers where they used the FDBM, they mostly fitted the parameters to some DFT calculations, with quite some range in the optimal parameters. Currently, we have set them as prefactor=18, exponent=1.0, which is what the Perez group used as fixed values in their QUAM-AFM database.

**Comment by ondrejkrejci** [comment] 2024-02-09 20:58
@NikoOinonen could you please specify DFT code, basis set and XC for the calculations for Fig. 2?
@mondracek could you specify the same for your system?
My personal guess is that the problem could be there.

**Comment by ondrejkrejci** [comment] 2024-02-13 13:46
> @mondracek ran the DFT for the potential/density in Fig. 2, so I'm guessing they are the same.
> 
> I did not use the default Pauli parameters in that figure, however. There they were prefactor = 12, and exponent = 1.2.

@NikoOinonen - So my guess is that you have used _FHI-aims_ with _PBE_ and Tkatchenko-Schefler for vdW. Isn't it? Would you be so kind to send the input files (control.in) to @mondracek , to see, if there are some differences in the options. Thank you!

**Comment by NikoOinonen** [comment] 2024-02-14 07:31
@ondrejkrejci Yes, I used the PBE parameters for D3, but FHI-aims was not used in any part of the calculation. Martin ran all the systems with VASP I believe.

**Comment by mondracek** [comment] 2024-02-26 16:59
Here is a figure with forces on H2O, comparing vdW-D2, vdW-D3 and Lennard-Jones. The full, dashed and dotted lines correspond to tip positions above the O atom of an H2O molecule with H atoms pointing down (in the xz-plane), above the O atom of a flat-lying (xy-plane) H2O molecule, and above an H atom of the same molecule, respectively.
<img width="396" alt="F_O-in-H2O" src="https://github.com/Probe-Particle/ppafm/assets/15730923/f1107be3-6db6-4303-b246-49c323420d8c">
I can upload the source data and input files for the simulations, if needed.

**Comment by NikoOinonen** [comment] 2024-02-27 08:13
> I have now checked our paper and we claim the prefactor for the Pauli interaction to be A=1.2 there, instead of A=12 as you state above

I see there is a typo in the figure caption. In the text it's correct, so A = 12.

**Comment by mondracek** [comment] 2024-02-29 15:06
I am now trying to compare the forces from`ppafm` to DFT (enhanced with the standard vdW corrections as implemented in VASP). This issue is going to be more complicated then I imagined at the beginning. Anyway, I am not sure anymore there is literally a bug in our code. So I changed the label to *possibly bug*.  What is clear so far is just that
* D2 and D3 vdW corrections are very different from each other
* D2 is reasonably similar to LJ
* D3 is very weak compared to D2 or LJ, but does not seem to be that different from Tkatchenko-Scheffler's correction as implemented in VASP. But this last point is currently a work in progress...

I need to run yet more DFT tests to understand what is going on. So, I am writing this comment to let you know what is the current status of the issue and that I am working on it, though there will be probably not much of contributions in the next few days, until I have the DFT results ready.

**Comment by yakutovicha** [comment] 2024-05-14 08:19
@mondracek will check the issue again and close it if it is not relevant. Maybe add a small documentation section with images.

**Comment by mondracek** [comment] 2024-07-16 14:17
Update to my previous comments:
* There is actually *no* vdW D2 correction implemented in PPAFM, only D3. So the D2 vs D3 comparison is moot. What I treated as D2 in PPAFM in my previous attempts was in fact the attractive part of the Lennard-Jones (LJ) interaction, but such a replacement of the D2 dispersion force model by LJ is not legitimate.
* D3 as implemented in PPAFM approximates both Tkatchenko-Scheffler correction and D2 correction implemented in VASP reasonably well. D3 is available only in the newer versions of VASP which are not available to me, so I cannot make a direct PPAFM vs VASP comparison for D3, unfortunately.
* There seems to be a systematic discrepancy between forces calculated with FDBM + vdW-D3 in PPAFM and DFT(PBE)-D3 in VASP in that the attractive forces are substantially weaker in PPAFM than they are in VASP This holds for several model systems in which the sample is represented by a free-standing atom or molecule. Nevertheless, the discrepancy does *not* originate from the van der Waals correction. If we wanted to address this, we should reopen the problem as a different issue.

Below, I will post a collection of figures showing the PPAFM vs VASP comparison of forces.
Note: A=18 and B=1 were used as parameters of the Pauli repulsion in all the below graphs.

**Comment by mondracek** [comment] 2024-07-16 14:28
Total forces including van der Waals for 6 different model systems, 4 molecules (benzene, bromomethane, carbon monoxide, and water) and 2 atoms (He, Xe). The tip is always a CO molecule, with the oxygen atom pointing towards the sample. On the molecules, the tip is placed over the C (in  benzene), Br (in bromomethane), and O (in CO and H2O) atoms, respectively. The benzene and H2O molecules are flat-lying, CH3Br points with the Br atom towards the tip, CO is in an upright position wit the O atom pointing towards the tip.

<img width="396" alt="C6H6+CO_Ftot" src="https://github.com/user-attachments/assets/d9c340ec-afe3-45a5-a45c-40786aad2d2e">
<img width="396" alt="CH3Br+CO_Ftot" src="https://github.com/user-attachments/assets/18d45102-a833-4f00-8f97-211c717c8747">
<img width="396" alt="CO+CO_Ftot" src="https://github.com/user-attachments/assets/9017f48c-2d50-4ecd-9e3b-eaec598cfe67">
<img width="396" alt="H2O+CO_Ftot" src="https://github.com/user-attachments/assets/63032462-2ebd-4398-8a74-8705da72997c">
<img width="396" alt="He+CO_Ftot" src="https://github.com/user-attachments/assets/24352146-c668-4030-bd07-259b125972a3">
<img width="396" alt="Xe+CO_Ftot" src="https://github.com/user-attachments/assets/ea1b892f-29c0-4056-8d60-d2b8402720dd">

**Comment by mondracek** [comment] 2024-07-16 14:32
Van der Waals components only for comparison. This demonstrates that the D3 model of dispersion forces as implemented in PPAFM agrees reasonably well with the dispersion forces implemented in VASP.

<img width="396" alt="C6H6+CO_FvdW" src="https://github.com/user-attachments/assets/088b1db4-499b-43b9-9173-245f4a051404">
<img width="396" alt="CH3Br+CO_FvdW" src="https://github.com/user-attachments/assets/f6239c92-3357-4925-9360-d53cd7927fe8">
<img width="396" alt="CO+CO_FvdW" src="https://github.com/user-attachments/assets/b1af8a85-4f31-4f9e-add4-3fba2d43fcd5">
<img width="396" alt="H2O+CO_FvdW" src="https://github.com/user-attachments/assets/581adca4-7f64-4e17-bccf-2fde6a7435fa">
<img width="396" alt="He+CO_FvdW" src="https://github.com/user-attachments/assets/17ad1cea-4ec9-4b2e-af90-4aa695e48429">
<img width="396" alt="Xe+CO_FvdW" src="https://github.com/user-attachments/assets/32813015-3822-4080-a032-be85cb659a3d">

**Comment by mondracek** [comment] 2024-07-16 14:35
Forces without the van der Waals component. This shows the discrepancy between FDBM of PPAFM and VASP while also demonstrating that the problem is not with the dispersion (vdW) forces but somewhere else.

<img width="396" alt="C6H6+CO_F-noVDW" src="https://github.com/user-attachments/assets/555ab1af-db18-4767-bc4e-a015d15fdbc2">
<img width="396" alt="CH3Br+CO_F-noVDW" src="https://github.com/user-attachments/assets/ee261a4d-1f31-4958-9a20-348f7d736c26">
<img width="396" alt="CO+CO_F-noVDW" src="https://github.com/user-attachments/assets/b3c7f8b8-a3d3-4339-be26-da4971dedcdb">
<img width="396" alt="H2O+CO_F-noVDW" src="https://github.com/user-attachments/assets/0a7c68db-f10c-43c3-b058-c95108fbc5bc">
<img width="396" alt="He+CO_F-noVDW" src="https://github.com/user-attachments/assets/d656a15f-6007-4256-8eb5-8ff841c1686d">
<img width="396" alt="Xe+CO_F-noVDW" src="https://github.com/user-attachments/assets/9d2b4c11-9ad0-4165-be03-85c77f1851cb">

**Comment by mondracek** [comment] 2024-07-16 14:41
This issue is ready to be closed. I will leave it hanging here open for a while so that there is a chance anyone notices the above figures.
Question: Should I just leave the figures here or move them, for example, to a newly created Wiki page dedicated to them? I do not feel like these figures need to be part of the documentation but if you guys think otherwise, I can make that Wiki page. Comments?

**Comment by ondrejkrejci** [comment] 2024-07-23 18:33
First of all - interesting that D32and TS do not match on CO-OC data - isn't there tilt of one of the CO molecules on D2?

What really surprises me is the huge difference between DFT and FDBM probably caused by charge (and multipole ) induction. I have no idea how to add these into the code easily. Probably some inspiration from classical force-fields or to try to go with some graph NN machine-learning force-field as an example in further future could be also an interesting project.

- I agree with closing this issue.
- I would really put these images on some dedicated wikipage as this could be really interesting.

**Comment by mondracek** [comment] 2024-07-24 08:40
@ondrejkrejci Oops, there is a mistake in the CO-OC plot. I have put the van-der-Waals-only component there instead of the total force for DFT-D2. I will fix this.

**Comment by ondrejkrejci** [comment] 2024-08-06 09:06
Hi @mondracek - I have added all your images to forces description: https://github.com/Probe-Particle/ppafm/wiki/Forces#comparison-of-dft-vs-original-l-j-vs-fdbm-d3-implementation ; Thus we have all the important information both for us and also users, if they need it. Thank you for working on it!

**Closed by ondrejkrejci** 2024-08-06 09:06 UTC
Labels: documentation, possibly_bug

**Comment by NikoOinonen** [comment] 2024-08-06 10:11
I missed this since I was on holiday.

Good to see that the D3 is working more or less as expected, at least in the far range where it's the most relevant. And it actually should not completely agree in the close range, because in our implementation the probe particle does not count towards the bonding configuration of the sample, which it would in the DFT codes.

At the close repulsive range the FDBM seems to work pretty well, but I had no clue the discrepancy is so large in the middle range. In the original paper by Ellner et al. (https://pubs.acs.org/doi/pdf/10.1021/acsnano.8b08209) they show a good match, but conveniently it's only shown in the 2.8-3.4Å range. Still, I wonder if the match could be better with a different choice of the FDBM parameters.

**Comment by ondrejkrejci** [comment] 2024-08-06 10:37
@NikoOinonen - yes, in here, we can see that already at 3.5 D2 and FDBM-D3 starts to overlay:
<img width="396" alt="C6H6+CO_Ftot" src="https://github.com/user-attachments/assets/d9c340ec-afe3-45a5-a45c-40786aad2d2e">
<img width="396" alt="CO+CO_Ftot" src="https://github.com/user-attachments/assets/de20dc47-17ae-4b2c-b3ef-27e60b56a106">
Both of those systems, are similar to what they had there. My personal guess is that they had a big discrepancies before and that is why they are not showing it, with motivation that bright lines are caused by repulsion and that the attractive forces are way weaker than the repulsive once. Thus we should be careful, where to fit those parameters ... 

Onset of (even week) chemical interaction + inductional electrostatics (~1/r^4) are here to blame (my opinion).
